INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('11', '111');
INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('22', '222');
INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('33', '333');

INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('영화', '댓글1');
INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('음식', '댓글2');
INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('취미', '댓글3');

INSERT INTO COMMENT (ARTICLE_ID, NICKNAME, BODY) VALUES (4, 'SHIN', '닥터스트레인지');
INSERT INTO COMMENT (ARTICLE_ID, NICKNAME, BODY) VALUES (4, 'KIM', '범죄도시2');
INSERT INTO COMMENT (ARTICLE_ID, NICKNAME, BODY) VALUES (4, 'LEE', '연애의온도');

INSERT INTO COMMENT (ARTICLE_ID, NICKNAME, BODY) VALUES (5, 'SHIN', '치킨');
INSERT INTO COMMENT (ARTICLE_ID, NICKNAME, BODY) VALUES (5, 'KIM', '피자');
INSERT INTO COMMENT (ARTICLE_ID, NICKNAME, BODY) VALUES (5, 'LEE', '훠궈');

INSERT INTO COMMENT (ARTICLE_ID, NICKNAME, BODY) VALUES (6, 'SHIN', '축구');
INSERT INTO COMMENT (ARTICLE_ID, NICKNAME, BODY) VALUES (6, 'KIM', '야구');
INSERT INTO COMMENT (ARTICLE_ID, NICKNAME, BODY) VALUES (6, 'LEE', '농구');