INSERT INTO ARTICLE (ID, TITLE, CONTENT) VALUES (1, '11', '111');
INSERT INTO ARTICLE (ID, TITLE, CONTENT) VALUES (2, '22', '222');
INSERT INTO ARTICLE (ID, TITLE, CONTENT) VALUES (3, '33', '333');

INSERT INTO ARTICLE (ID, TITLE, CONTENT) VALUES (4, '영화', '댓글1');
INSERT INTO ARTICLE (ID, TITLE, CONTENT) VALUES (5, '음식', '댓글2');
INSERT INTO ARTICLE (ID, TITLE, CONTENT) VALUES (6, '취미', '댓글3');

INSERT INTO COMMENT (ID, ARTICLE_ID, NICKNAME, BODY) VALUES (1, 4, 'SHIN', '닥터스트레인지');
INSERT INTO COMMENT (ID, ARTICLE_ID, NICKNAME, BODY) VALUES (2, 4, 'KIM', '범죄도시2');
INSERT INTO COMMENT (ID, ARTICLE_ID, NICKNAME, BODY) VALUES (3, 4, 'LEE', '연애의온도');

INSERT INTO COMMENT (ID, ARTICLE_ID, NICKNAME, BODY) VALUES (4, 5, 'SHIN', '치킨');
INSERT INTO COMMENT (ID, ARTICLE_ID, NICKNAME, BODY) VALUES (5, 5, 'KIM', '피자');
INSERT INTO COMMENT (ID, ARTICLE_ID, NICKNAME, BODY) VALUES (6, 5, 'LEE', '훠궈');

INSERT INTO COMMENT (ID, ARTICLE_ID, NICKNAME, BODY) VALUES (7, 6, 'SHIN', '축구');
INSERT INTO COMMENT (ID, ARTICLE_ID, NICKNAME, BODY) VALUES (8, 6, 'KIM', '야구');
INSERT INTO COMMENT (ID, ARTICLE_ID, NICKNAME, BODY) VALUES (9, 6, 'LEE', '농구');